# GitHub Actions Workflow
# https://help.github.com/actions

name: build
on: [push, pull_request]
env:
  CI: true
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install --immutable-cache
      - run: yarn workspace @example/api lint
      - run: yarn workspace @example/api test
      - run: yarn workspace @example/api build
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install --immutable-cache
      - run: yarn workspace @example/web lint
      - run: yarn workspace @example/web test
      - run: yarn workspace @example/web build